import type { Metadata } from "next";
import { Lato , Playfair_Display } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/navbar";
import { Footer } from "@/components/Footer";
import { Provders } from "./provider";
import { Toaster } from "react-hot-toast";

const lato_init = Lato({
  subsets: ["latin"],
  weight:['100' , '300' , '400', '700'],
  variable: '--font-lato'
})

const playfair_display = Playfair_Display({
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: '--font-playfair'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  
   

  return (
    

    <html lang="en">
      <body className={`${lato_init.variable} ${playfair_display.variable} bgimage`}>
        <Provders>
        <NavBar/>
        <div><Toaster/></div>
        {children}
        <Footer/>
        </Provders>
        </body>
    </html>
  );
}
